var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "일",
            "sun": "일",
            "mon": "월",
            "tue": "화",
            "wed": "수",
            "thu": "목",
            "fri": "금",
            "sat": "토",
            "jan": "1월",
            "feb": "2월",
            "mar": "3월",
            "apr": "4월",
            "may": "5월",
            "jun": "6월",
            "jul": "7월",
            "aug": "8월",
            "sep": "9월",
            "oct": "10월",
            "nov": "11월",
            "dec": "12월"
        },
        "no_implemented": "준비중입니다",
        "to_date_view": "오늘 날짜를 보려면 누르세요",
        "i_undefined": "정의되지 않음",
        "allday_event": "하루 종일 일정",
        "repeat_event": "반복 일정",
        "time": "시간",
        "event": "예약",
        "location": "장소",
        "participant": "참여자",
        "get_data_exception": "예외 발생",
        "new_event": "새 예약",
        "confirm_delete_event": "삭제 합니까? ",
        "confrim_delete_event_or_all": "모든 예약이나 이번 건을 반복합니까? \r\n [완료]를 누르면 이 예약만 삭제되고, [취소]를 누르면 모든 예약이 삭제됩니다",
        "data_format_error": "형식이 틀렸습니다! ",
        "invalid_title": "예약 제목은 공백이나 ($<>)를 포함할 수 없습니다.",
        "view_no_ready": "처리 중 입니다.",
        "example": "내용을 입력하세요.",
        "content": "내용",
        "create_event": "일정 만들기",
        "update_detail": "세부 입력하기",
        "click_to_detail": "상세 보기",
        "i_delete": "삭제",
        "day_plural": "일정",
        "others": "다른 일정",
        "item": ""
    }
});
